version: 2
jobs:

  test:
    working_directory: /code
    docker:
      - image: python:3.6
      - image: postgres
        name: db
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d /code/.venv ]]; then
              python -m venv /code/.venv
              . /code/.venv/bin/activate
              python setup.py develop
            fi
      - run:
          name: Test
          command: |
            . /code/.venv/bin/activate
            python setup.py test
      - save_cache:
          key: deps-{{ checksum "setup.py" }}
          paths:
            - /code/.venv
            - /code/.eggs
  deploy:
    working_directory: ~/crowdsourcing
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deploy-{{ checksum "setup.py" }}
      - run:
          name: Install Requirements
          command: |
            apk add --no-cache python3
      - run:
          name: Deploy
          command: |
            if [[ "${CIRCLE_BRANCH}" == "demo" ]]; then
              python3 setup.py deploy --environment=demo \
                                     --tag=demo \
                                     --ecs-cluster=microservices \
                                     --ecr-repository=crowdsourcing \
                                     --wait=300
            elif echo "$CIRCLE_TAG" | grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
              python3 setup.py deploy --environment=prod \
                                     --tag="$CIRCLE_TAG" \
                                     --ecs-cluster=microservices \
                                     --ecr-repository=crowdsourcing \
                                     --wait=300
             fi
      - save_cache:
          key: deploy-{{ checksum "setup.py" }}
          pathes:
            - ~/crowdsourcing/.eggs
            - ~/.cache

  deploy_static:
    working_directory: /code
    docker:
      - image: python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d /code/.venv ]]; then
              python -m venv /code/.venv
              . /code/.venv/bin/activate
              python setup.py requirements
            fi
      - run:
          name: Deploy Static
          command: |
            . /code/.venv/bin/activate
            python setup.py develop
            set -o allexport
            if [[ "${CIRCLE_BRANCH}" == "demo" ]]; then
              env | grep ^DEMO_ | sed 's/DEMO_//g' > .env && source .env
              manage.py collectstatic --no-input
            elif echo "$CIRCLE_TAG" | grep -qP "v\d+\.\d+\.\d+"; then
              env | grep ^PROD_ | sed 's/PROD_//g' > .env && source .env
              manage.py collectstatic --no-input
            fi
            set +o allexport

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: demo
      - deploy_static:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: demo

experimental:
  notify:
    branches:
      only:
        - master
