---
deploy_steps: &deploy_steps
  working_directory: ~/crowdsourcing
  docker:
    - image: circleci/python:3.7
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: v2-{{ checksum "setup.py" }}
    - run:
        name: Deploy
        command: |
          TAG=${CIRCLE_TAG:-demo}
          . ~/.venv/bin/activate
          python setup.py deploy \
            --cpu=256 \
            --ecr-repository=crowdsourcing \
            --ecs-cluster=microservices \
            --environment=$ENV \
            --execution-role="ecsTaskExecutionRole" \
            --fargate \
            --memory-reservation=512 \
            --migrate='./manage.py migrate --noinput' \
            --ports=8080 \
            --tag=$TAG \
            --task-role=crowdsourcing-$ENV \
            --wait=300

deploy_static_steps: &deploy_static_steps
  working_directory: ~/crowdsourcing
  docker:
    - image: circleci/python:3.7
  steps:
    - checkout
    - restore_cache:
        key: v2-{{ checksum "setup.py" }}
    - run:
        name: Deploy Static
        command: |
          . ~/.venv/bin/activate
          pip install -e .
          set -o allexport
          env | grep "^${ENV}_" | sed "s/${ENV}_//g" > .env && source .env
          manage.py collectstatic --no-input
          set +o allexport

version: 2
jobs:

  test:
    working_directory: ~/crowdsourcing
    docker:
      - image: circleci/python:3.7
      - image: postgres
        name: db
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ checksum "setup.py" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python -m venv ~/.venv
              . ~/.venv/bin/activate
              pip install -e .
              python setup.py test_requirements
            fi
      - run:
          name: Test
          command: |
            . ~/.venv/bin/activate
            wait-for-it.sh -h db -p 5432 -t 30
            python setup.py test
      - save_cache:
          key: v2-{{ checksum "setup.py" }}
          paths:
            - ~/.venv
            - ~/crowdsourcing/.eggs
            - ~/crowdsourcing/crowdsourcing.egg-info

  deploy_prod:
    <<: *deploy_steps
    environment:
      ENV: prod

  deploy_demo:
    <<: *deploy_steps
    environment:
      ENV: demo

  deploy_static_prod:
    <<: *deploy_static_steps
    environment:
      ENV: PROD

  deploy_static_demo:
    <<: *deploy_static_steps
    environment:
      ENV: DEMO

workflows:
  version: 2
  just-test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
  deploy-demo:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy_demo:
          requires:
            - test
      - deploy_static_demo:
          requires:
            - test
  deploy-prod:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy_prod:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy_static_prod:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
