version: '3'

services:
  db:
    image: postgres
  django:
    build: .
    command: ["./scripts/run_dev"]
    depends_on:
      - db
    environment:
      - AWS_STORAGE_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - DJANGO_DEBUG=true
      - DJANGO_SECRET_KEY=dev
      - DJANGO_URL_PREFIX
      - CLIENT_URL_PREFIX
    image: nypr-crowdsourcing
    links:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./crowdsourcing:/code/crowdsourcing
      - ./scripts:/code/scripts
      - ./surveys:/code/surveys
      - ./templates:/code/templates
      - ./manage.py:/code/manage.py
      - ./setup.py:/code/setup.py
      - ./pytest.ini:/code/pytest.ini
