version: '3'

services:
  db:
    image: postgres
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    depends_on:
      - db
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_SECRET_KEY: dev
    image: nypr-crowdsourcing
    links:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./crowdsourcing:/code/crowdsourcing
      - ./scripts:/code/scripts
      - ./surveys:/code/surveys
      - ./templates:/code/templates 
      - ./manage.py:/code/manage.py
      - ./setup.py:/code/setup.py
      - ./pytest.ini:/code/pytest.ini
