# Generated by Django 2.0.1 on 2018-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_field_lengths_type_and_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='brand_link',
            field=models.URLField(blank=True, verbose_name='Brand Link'),
        ),
        migrations.AddField(
            model_name='survey',
            name='brand_link_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link Text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='brand_logo',
            field=models.ImageField(blank=True, upload_to='media/surveys/logos', verbose_name='Brand Logo'),
        ),
    ]
