# Generated by Django 2.0.1 on 2018-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_field_lengths_type_and_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ends At'),
        ),
    ]
