#!/usr/bin/env bash

[ -n "$DJANGO_SECRET_KEY" ] || { echo "Need to set env var DJANGO_SECRET_KEY" > /dev/stderr && exit 1; }

ini=/code/uwsgi.ini
export SERVICE=crowdsourcing

uwsgi \
    --ini "${ini}" \
    --env DJANGO_SETTINGS_MODULE=crowdsourcing.settings \
    --env DJANGO_DEBUG=False \
    --env DJANGO_URL_PREFIX=/crowdsourcing \
    --mount /crowdsourcing=crowdsourcing.wsgi:application
