#!/usr/bin/env bash
ini=/code/uwsgi.ini
export SERVICE=crowdsourcing
export DJANGO_SETTINGS_MODULE=crowdsourcing.settings
export DJANGO_DEBUG=True

wait-for-it.sh -h "${DB_HOST:-db}" -p "${DB_PORT:-5432}" -t 30

python manage.py migrate
python setup.py test_requirements
python manage.py runserver 0.0.0.0:8080
